site_name: Flux Connectors
# site_url: https://example.com
site_description: Documentation for My Project

theme:
  name: material
  icon:
    logo: fontawesome/solid/f
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: blue
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  
  features:
    - navigation.instant

nav:
  - Home: index.md
  - Blog: blog/index.md
  - Quick Start: quick_start.md
  - Code:
    - Code examples: code/code_example.md
    - API: code/API.md
    - Code structure: 
      - Overall structure: code/class_structure/structure.md
      - Base class: code/class_structure/base_class.md
      - Walkthrough: code/class_structure/walkthrough.md


# Enable useful markdown extensions (e.g. admonition) and configure Mermaid fences
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - admonition

plugins:
  - search
  - blog:
      enabled: true
      blog_dir: blog
      blog_toc: false
      post_dir: "{blog}/posts"
      post_url_max_categories: 1
      post_slugify_separator: "-"
      post_excerpt_max_authors: 1
      post_excerpt_max_categories: 5
      post_excerpt_separator: <!-- more -->
      post_readtime: true
      post_readtime_words_per_minute: 265
      pagination: true
      pagination_per_page: 10
      pagination_keep_content: false
      draft: false
      draft_on_serve: true
      draft_if_future_date: false
  # Option 1: Use Mermaid integration (supported natively by Material)
  # - mermaid2s

